export const controlRanges = {
  iterations: { min: 1, max: 10, step: 1 },
  rotationSpeed: { min: 0.1, max: 4, step: 0.1 },
  zoomScale: { min: 1, max: 4, step: 0.1 },
  colorSaturation: { min: 0.2, max: 1, step: 0.01 },
  colorBrightness: { min: 1000, max: 3000, step: 100 },
  distortX: { min: 1, max: 8, step: 0.1 },
  distortY: { min: 1, max: 6, step: 0.1 },
  distortZ: { min: 1, max: 6, step: 0.1 },
  dotScale: { min: 4, max: 12, step: 0.1 },
  waveAmplitude: { min: 0, max: 2, step: 0.1 },
  waveFrequency: { min: 0, max: 5, step: 0.1 },
  spiralIntensity: { min: 0, max: 2, step: 0.1 },
  noiseScale: { min: 0, max: 0, step: 0 },
  symmetryCount: { min: 1, max: 12, step: 1 },
  kaleidoscopeAngle: { min: 0, max: Math.PI * 2, step: 0.1 },
  colorCycle: { min: 0, max: 1, step: 0.01 },
  colorContrast: { min: 0.5, max: 2, step: 0.1 },
  colorShift: { min: 0, max: 1, step: 0.01 },
  depthScale: { min: 0.5, max: 2, step: 0.1 },
  turbulence: { min: 0, max: 2, step: 0.1 },
  swirl: { min: 0, max: 2, step: 0.1 },
  pulseRate: { min: 0, max: 2, step: 0.1 },
  pulseAmplitude: { min: 0, max: 1, step: 0.1 },
  // Enhanced Fractalization Controls
  fractalization: { min: 0.1, max: 5.0, step: 0.1 },
  fractalDepth: { min: 1, max: 8, step: 0.5 },
  fractalDetail: { min: 0.1, max: 2.0, step: 0.1 },
  fractalComplexity: { min: 0.1, max: 3.0, step: 0.1 },
  fractalDimension: { min: 1.0, max: 3.0, step: 0.1 },
  // Enhanced Tessellation Controls
  tessellation: { min: 0.1, max: 5.0, step: 0.1 },
  tesselationScale: { min: 0.1, max: 4.0, step: 0.1 },
  tesselationDensity: { min: 1, max: 10, step: 0.5 },
  tesselationPattern: { min: 1, max: 5, step: 1 },
  tesselationRotation: { min: 0, max: Math.PI * 2, step: 0.1 },
  // Other Controls
  morphScale: { min: 0, max: 1, step: 0.05 },
  timeScale: { min: 0.1, max: 2, step: 0.1 },
  glowIntensity: { min: 0, max: 1, step: 0.1 },
  shadowDepth: { min: 0, max: 1, step: 0.1 }
};